version: '3'
services:
  opensearch-node1:
    image: opensearchproject/opensearch:2.19.0
    ports:
      - "9200:9200"
      - "9600:9600"
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - node.name=opensearch-node1
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Xcaliber#7#
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    networks:
      - opensearch-net
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.19.0
    ports:
      - "5601:5601"
    expose:
      - "5601"
    depends_on:
      - opensearch-node1
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200"]' # must be a string with no spaces when specified as an environment variable
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: Xcaliber#7#
    networks:
      - opensearch-net

  postgres:
    image: postgres:latest
    ports:
    - "5432:5432"
    expose:
    - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres0
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_init:/var/lib/docker-entrypoint-initdb.d/

  redis:
    image: redis:latest
    container_name: "redis_cache"
    ports:
    - "6379:6379"
    expose:
    - 6379

    volumes:
    - redis_data:/varlib/rediscache/data

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Web UI
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: Xcaliber#7#
    volumes:
      - ./minio-data:/var/lib/minio/data

  # backend:
  #  build: 
  #    context: .
  #  ports:
  #  - "8080:8080"
  #  working_dir: /app
  #  volumes:
  #  - ./search:/app/search
  #  -  nltk_data:/root/nltk_data
  #  command: bash -c "cd search && bash start_server.sh 0.0.0.0 8080"
  #  expose:
  #  - 8080

volumes:
  opensearch-data1:
  postgres_data:
  postgres_init:
  redis_data:
  minio-data:
  nltk_data:

networks:
  opensearch-net: